#!/bin/bash
# SPDX-License-Identifier: Apache-2.0
# (c) Copyright 2021 - 2022 Xilinx, Inc. All rights reserved.

. ${SF_TS_CONFDIR}/make_cmds
. ${SF_TS_CONFDIR}/scripts/fix-ssh-keys-perm
. ${SF_TS_CONFDIR}/scripts/lib

export TE_IUT_TA_NAME="NetDrv"
export TE_TST1_TA_NAME="Peer"
export TE_HYPERVISOR_TA_NAME="Hypervisor"
export TE_LOG_LISTENER_TA_NAME="LogListener"
export TE_TA_SIGNATURE_FIELDS="gcc-target kernel-version-full libc-version header-version"

if test -z "${TE_LOG_LISTENER}" -a -n "${TE_TST3}" ; then
    # For many OL hosts TE_LOG_LISTENER is not defined explicitly,
    # instead TE_TST3 host is used for serial console logs gathering.
    # It can be used here for netconsole logs gathering as well.
    export TE_LOG_LISTENER=${TE_TST3}
    export TE_LOG_LISTENER_NETCONSOLE_IUT=yes
    export TE_LOG_LISTENER_NETCONSOLE_TST1=yes
fi

source "${TE_BASE}"/engine/builder/te_ta_ssh_helper

: ${TS_TEST_AGENTS:=TE_IUT TE_TST1 TE_HYPERVISOR TE_LOG_LISTENER}

te_ta_list_detect_type_with_signature ${TS_TEST_AGENTS}

export_headers_num "TE_IUT"
export_headers_num "TE_TST1"
export_headers_num "TE_HYPERVISOR"
export_headers_num "TE_LOG_LISTENER"
export_kernel_version_num "TE_IUT"
