#!/bin/bash
# SPDX-License-Identifier: Apache-2.0
# (c) Copyright 2021 - 2022 Xilinx, Inc. All rights reserved.
set -e

export TS_TOPDIR="$(cd "$(dirname "$(which "$0")")/.."; pwd -P)"
. ${TS_TOPDIR}/scripts/guess.sh

doxygen_debug=false

do_default=true
do_pdf=false
do_html=false
doc_language=""

help() {
    cat <<EOF
Tool is used to generate documentation for the net-drv-ts test suite.

It's based on doxygen and doxyrest.

Usage: ./$0 [--help] [--debug] [--html] [--pdf] [--lang=LANG]

Options:
    --html: generate html documentation (default)
    --pdf: generate pdf documentation
    --debug: enable debug mode
    --lang=LANG: set Sphinx document language (e.g. en, ru)
    --help: show this help message
EOF
}

for opt ; do
    case "${opt}" in
        --help|-h)
            help
            exit 0
            ;;
        -d|--debug)
            doxygen_debug=true
            ;;
        --html)
            do_default=false
            do_html=true
            ;;
        --pdf)
            do_default=false
            do_pdf=true
            ;;
        --lang=*|--language=*)
            doc_language="${opt#*=}"
            ;;
        *)
            echo "Unknown option: $opt" >&2
            help
            exit 1
            ;;
    esac
done

if [ -z "$DOXYREST_PREFIX" ]; then
    $TE_BASE/scripts/doxyrest_deploy.sh --how
    exit -1
fi
[ -z "$DOXYREST_BIN" ] && DOXYREST_BIN="$DOXYREST_PREFIX/bin/doxyrest"

[ -z "$SPHINX_BUILD_BIN" ] && SPHINX_BUILD_BIN="sphinx-build"
if ! which $SPHINX_BUILD_BIN >/dev/null; then
    echo "Please install sphinx before:"
    echo " $ pip install sphinx sphinx_rtd_theme"
    exit -2
fi

pushd ${TS_TOPDIR} >/dev/null

if $doxygen_debug ; then
   doxygen -d extcmd -d filteroutput net-drv-ts/Doxyfile
else
    doxygen net-drv-ts/Doxyfile >/dev/null
fi

DOXYREST_OPTS=(
    --config=net-drv-ts/doc/doxyrest-config.lua
    --frame-dir=$DOXYREST_PREFIX/share/doxyrest/frame/cfamily
    --frame-dir=$DOXYREST_PREFIX/share/doxyrest/frame/common
)

${DOXYREST_BIN} "${DOXYREST_OPTS[@]}" || exit 1

if $do_default; then
    do_html=true
    do_pdf=false
fi

if $do_html; then
    SPHINX_BUILD_OPTS=(
        -j auto                         # use cpu count
        -q                              # be quite: warn and error only
    )
    if [ -n "$doc_language" ]; then
        SPHINX_BUILD_OPTS+=( -D "language=$doc_language" )
    fi
    SPHINX_BUILD_OPTS+=(
        net-drv-ts/doc                  # input
        net-drv-ts/doc/generated/html   # output
    )

    ${SPHINX_BUILD_BIN} "${SPHINX_BUILD_OPTS[@]}"
fi

if $do_pdf; then
    ${TE_BASE}/scripts/rst_adjust \
        --toctree-move-to-end \
        --refs-remove \
        --authors-strip \
        net-drv-ts/doc/generated/rst/group_*.rst

    if [ -n "$doc_language" ]; then PDF_SPHINXOPTS="-D language=$doc_language"; else PDF_SPHINXOPTS=""; fi
    make -C "${TS_TOPDIR}/net-drv-ts/doc" latexpdf SPHINXOPTS="$PDF_SPHINXOPTS"

    # Note, the name depends on conf.py!
    echo Open: $(realpath net-drv-ts/doc/generated/latex/net_driver_test_suite.pdf)
fi

popd >/dev/null
